### PR TITLE
Fix NPE when ALLOW_MOCK_LOCATION is missing

### LINKED ISSUE #25: app crashed on onePlus A3010
Fatal Exception: com.facebook.react.common.JavascriptException: Java exception in 'NativeModules'

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference, stack:
com.gantix.JailMonkey.JailMonkeyModule.isMockLocationOn@127
com.gantix.JailMonkey.JailMonkeyModule.getConstants@36
com.facebook.react.bridge.JavaModuleWrapper.getConstants@138
android.os.Handler.handleCallback@789
android.os.Handler.dispatchMessage@98
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage@29

### PR DESCRIPTION
**Pull request by lefloh**
This fixes #25 as described in the issue.
It would be really great if this could get merged as our app crashes currently on certain OnePlus devices.

### CODE REVIEW

**Comment by GantMan** [comment]
awesome!

**Comment by lefloh** [comment]
This was the fasted merge of a PR ever :)
Thanks a lot! 👍 
Do you have plans for the next release?

**Comment by GantMan** [comment]
2.1.0 released!

**Comment by lefloh** [comment]
Really awesome 🚀 Thanks a million 🎉

**Comment by lefloh** [comment]
Hi, seems like 2.1.0 is still not available at npm 🤔 
Any ideas?

**Comment by GantMan** [comment]
Sorry, npm 2.1.1 released and verified

**Comment by GantMan** [comment]
My shipping tool broke and gave a false positive.

**Comment by lefloh** [comment]
Awesome, thanks!

**Pull request merged**
