### PR TITLE
isDebugged

### PR DESCRIPTION
**Pull request by puskin94**
`isDebugged()` is a new method which allow the developer to understand if the application is running in debuggable mode or not.

### CODE REVIEW

**Comment by GantMan** [comment]
Can you fix the merge conflict?

**Comment by puskin94** [comment]
@GantMan Thanks for the support and for being so fast! I solved the conflicts

**Comment by GantMan** [comment]
awesome add!  Thanks!

**Comment by GantMan** [comment]
@puskin94 - can you update the README to include the new commands?  After that I can do a release.

**Pull request merged**
