### PR TITLE
Added macro to bypass check on simulators

### PR DESCRIPTION
**Pull request by chhourbro**

### CODE REVIEW

**Comment by GantMan** [comment]
awsome thanks!

**Comment by tangnv** [comment]
@GantMan did you release this change? I don't see changes in latest version 2.3.1

**Comment by GantMan** [comment]
I did not.  @tangnv - would you be interested in being a publisher on NPM?
I feel bad missing these tasks.  I could use some help.

**Comment by tangnv** [comment]
@GantMan ok, need you guide me a little bit

**Comment by GantMan** [comment]
No problem!  Sign up on https://www.npmjs.com/ and share your username with me.  I can explain pretty quickly.  :)

**Comment by tangten** [comment]
@GantMan my username is @tangten

**Comment by GantMan** [comment]
image
Once you accept, you will be able to update the version number in package.json and do an `npm publish` to push the code to NPM!

**Comment by tangten** [comment]
should we implement this one for Android as well @GantMan ?

**Comment by GantMan** [comment]
I believe so

**Comment by tangten** [comment]
ok let me create a new PR for that as well @GantMan

**Pull request merged**
